# Generated by Django 4.2.7 on 2026-01-31 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enrollment', models.BooleanField(default=True)),
                ('email_completion', models.BooleanField(default=True)),
                ('email_certificate', models.BooleanField(default=True)),
                ('email_payment', models.BooleanField(default=True)),
                ('email_quiz_result', models.BooleanField(default=True)),
                ('email_course_update', models.BooleanField(default=True)),
                ('email_system', models.BooleanField(default=True)),
                ('email_reminder', models.BooleanField(default=True)),
                ('app_enrollment', models.BooleanField(default=True)),
                ('app_completion', models.BooleanField(default=True)),
                ('app_certificate', models.BooleanField(default=True)),
                ('app_payment', models.BooleanField(default=True)),
                ('app_quiz_result', models.BooleanField(default=True)),
                ('app_course_update', models.BooleanField(default=True)),
                ('app_system', models.BooleanField(default=True)),
                ('app_reminder', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('enrollment', 'Course Enrollment'), ('completion', 'Course Completion'), ('certificate', 'Certificate Generated'), ('payment', 'Payment Processed'), ('quiz_result', 'Quiz Result'), ('course_update', 'Course Update'), ('system', 'System Notification'), ('reminder', 'Reminder')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('enrollment_id', models.IntegerField(blank=True, null=True)),
                ('quiz_id', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
