# Generated by Django 4.2.7 on 2026-01-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time_seconds', models.PositiveIntegerField(default=0)),
                ('total_watched_seconds', models.PositiveIntegerField(default=0)),
                ('watch_percentage', models.FloatField(default=0.0)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='enrollments.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='courses.lesson')),
            ],
            options={
                'db_table': 'video_progress',
                'indexes': [models.Index(fields=['enrollment', 'last_watched_at'], name='video_progr_enrollm_bc684b_idx')],
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='enrollments.enrollment')),
                ('lessons_accessed', models.ManyToManyField(related_name='study_sessions', to='courses.lesson')),
            ],
            options={
                'db_table': 'study_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['enrollment', 'started_at'], name='study_sessi_enrollm_1cc808_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp_seconds', models.PositiveIntegerField(blank=True, help_text='Video timestamp in seconds', null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enrollments.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='courses.lesson')),
            ],
            options={
                'db_table': 'student_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment', 'lesson'], name='student_not_enrollm_bc4d95_idx'), models.Index(fields=['lesson', 'timestamp_seconds'], name='student_not_lesson__b86b33_idx')],
            },
        ),
        migrations.CreateModel(
            name='LessonInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('play', 'Play Video'), ('pause', 'Pause Video'), ('seek', 'Seek Video'), ('speed_change', 'Change Playback Speed'), ('fullscreen', 'Enter Fullscreen'), ('note_create', 'Create Note'), ('bookmark_create', 'Create Bookmark'), ('quiz_start', 'Start Quiz'), ('quiz_complete', 'Complete Quiz')], max_length=20)),
                ('timestamp_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='enrollments.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='courses.lesson')),
            ],
            options={
                'db_table': 'lesson_interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment', 'lesson', 'interaction_type'], name='lesson_inte_enrollm_24292c_idx'), models.Index(fields=['created_at'], name='lesson_inte_created_e0861e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LessonBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('timestamp_seconds', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='enrollments.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='courses.lesson')),
            ],
            options={
                'db_table': 'lesson_bookmarks',
                'ordering': ['timestamp_seconds'],
                'indexes': [models.Index(fields=['enrollment', 'lesson'], name='lesson_book_enrollm_10b8fd_idx')],
                'unique_together': {('enrollment', 'lesson', 'timestamp_seconds')},
            },
        ),
    ]
