# Generated by Django 4.2.7 on 2026-01-28 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell students about yourself')),
                ('skills', models.TextField(blank=True, help_text='List your skills and expertise areas')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/')),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('education', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'db_table': 'teacher_profiles',
            },
        ),
        migrations.CreateModel(
            name='TeacherVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_id', models.FileField(help_text='Upload a clear photo of your government-issued ID', upload_to='verification/government_ids/')),
                ('portfolio', models.FileField(help_text='Upload your portfolio or resume (PDF format preferred)', upload_to='verification/portfolios/')),
                ('demo_video', models.FileField(help_text='Upload a short demo video showcasing your teaching skills', upload_to='verification/demo_videos/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('review_notes', models.TextField(blank=True, help_text='Admin notes about the verification')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'Teacher Verification',
                'verbose_name_plural': 'Teacher Verifications',
                'db_table': 'teacher_verifications',
            },
        ),
    ]
