# Generated by Django 4.2.7 on 2026-01-28 10:49

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total revenue from all course sales', max_digits=12)),
                ('total_net_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net earnings after platform commission', max_digits=12)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid out to teacher', max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available balance for payout', max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Platform commission percentage', max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Earnings',
                'verbose_name_plural': 'Teacher Earnings',
                'db_table': 'teacher_earnings',
            },
        ),
        migrations.CreateModel(
            name='TeacherBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account')], default='checking', max_length=20)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='US', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Bank Account',
                'verbose_name_plural': 'Teacher Bank Accounts',
                'db_table': 'teacher_bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('external_transaction_id', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='teachers.teacherbankaccount')),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payout_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earning_transactions', to='courses.course')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning_transaction', to='payments.payment')),
                ('payout_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='teachers.payoutrequest')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='earning_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payout_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'is_paid_out'], name='payout_tran_teacher_06eec2_idx'), models.Index(fields=['course', 'created_at'], name='payout_tran_course__12b1a9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['teacher', 'status'], name='payout_requ_teacher_f8db8b_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status', 'requested_at'], name='payout_requ_status_7d2657_idx'),
        ),
    ]
