# Generated by Django 4.2.7 on 2026-01-28 06:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Course title', max_length=200)),
                ('description', models.TextField(help_text='Detailed course description')),
                ('short_description', models.CharField(help_text='Brief course summary', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('business', 'Business'), ('marketing', 'Marketing'), ('data_science', 'Data Science'), ('photography', 'Photography'), ('music', 'Music'), ('language', 'Language'), ('health', 'Health & Fitness'), ('other', 'Other')], max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('learning_outcomes', models.TextField(help_text='What students will learn (one per line)')),
                ('prerequisites', models.TextField(blank=True, help_text='Course prerequisites')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('duration_hours', models.PositiveIntegerField(default=0, help_text='Estimated course duration')),
                ('language', models.CharField(default='English', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(limit_choices_to={'is_verified': True, 'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'db_table': 'course_sections',
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lesson_type', models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='video', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('video_url', models.URLField(blank=True, help_text='Video file URL (S3 or external)')),
                ('video_duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('text_content', models.TextField(blank=True, help_text='Text lesson content')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_preview', models.BooleanField(default=False, help_text='Can be viewed without enrollment')),
                ('is_required', models.BooleanField(default=True, help_text='Required for course completion')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursesection')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['section', 'order'], name='lessons_section_918079_idx')],
                'unique_together': {('section', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'category'], name='courses_status_44e183_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'status'], name='courses_instruc_680c73_idx'),
        ),
    ]
